<?php
use Application\Model\Solicitante;
use Application\Model\Assunto;

$_SESSION['dados'] = ($_SESSION['dados'] ?? []);
$solicitante = $_SESSION['dados']['solicitante'] ?? new Solicitante([]);
$assunto = $_SESSION['dados']['assunto'] ?? new Assunto([]);
?>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Sistema de Atendimento a Demandas</title>
</head>
<body>
	<h3>Sistema de Atendimento a Demandas</h3>
	<?php
	if (isset($_SESSION['mensagem'])) :
?>
<p><?=$_SESSION['mensagem']?></p>			    
<?php
        unset($_SESSION['mensagem']);
	endif;	
	?>
	<div class="container">
	<form method="post" action="<?=$this->url('application',['action' => 'processar'])?>">
		<table>
			<tr>
				<td>CPF:</td>
				<td><input type="text" class="form-control" name="cpf" autofocus="autofocus" maxlength="11" value="<?=$solicitante->cpf?>"/></td>
			</tr>
			<tr>
				<td>Nome do solicitante:</td>
				<td><input type="text" class="form-control"  name="nome" value="<?=$solicitante->nome?>"/></td>
			</tr>
			<tr>
				<td>CEP:</td>
				<td><input type="text" class="form-control"  name="cep" value="<?=$solicitante->cep?>" maxlength="8" /></td>
			</tr>
			<tr>
				<td>Município:</td>
				<td><input type="text" class="form-control"  name="municipio" value="<?=$solicitante->municipio?>"/></td>
			</tr>
			<tr>
				<td>UF:</td>
				<td><input type="text" class="form-control"  name="uf" value="<?=$solicitante->uf?>" maxlength="2"/></td>
			</tr>
			</td>
			<tr>
				<td>E-mail:</td>
				<td><input type="email" class="form-control"  name="email" value="<?=$solicitante->email?>"/></td>
			</tr>
			<tr>
				<td>DDD:</td>
				<td><input type="number" class="form-control"  name="ddd" value="<?=$solicitante->ddd?>" maxlength="2"/></td>
			</tr>
			<tr>
				<td>Telefone:</td>
				<td><input type="text" class="form-control"  name="telefone" value="<?=$solicitante->telefone?>"/></td>
			</tr>
			<tr>
				<td>Assunto:</td>
				<td><input type="text" class="form-control"  name="assunto" value="<?=$assunto->assunto?>"/></td>
			</tr>
		</table>
		Detalhes:<br/>
		<textarea name="detalhes" class="form-control"  style="width:500px;" rows="10" cols="50">
<?=$assunto->detalhes?>		
</textarea><br/>
<?php
if (isset($_SESSION['dados']['detalhes_gravados'])):
?>
<p>Foi encontrado um assunto igual na base de demandas com estes detalhes:</p>
<p>
<?=$_SESSION['dados']['detalhes_gravados']?>
</p>
<?php
    unset($_SESSION['dados']['detalhes_gravados']);
endif;
?>   
		<input class="btn btn-success btn-lg" type="submit" value="gravar" />
	</form>
	</div>
</body>
</html>
<?php
$_SESSION['dados'] = [];
?>